ktor:
    application:
        modules:
            - com.idunnololz.summitForLemmy.server.ApplicationKt.module
    deployment:
        port: 8080
        postgres:
            username: $POSTGRES_USERNAME
            password: $POSTGRES_PASSWORD
